# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tinkar_search_pb2 as tinkar__search__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tinkar_search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TinkarSearchServiceStub(object):
    """gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/Search',
                request_serializer=tinkar__search__pb2.TinkarSearchQueryRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.ConceptSearch = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/ConceptSearch',
                request_serializer=tinkar__search__pb2.TinkarConceptSearchRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.ConceptSearchWithSort = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/ConceptSearchWithSort',
                request_serializer=tinkar__search__pb2.TinkarConceptSearchWithSortRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarConceptSearchWithSortResponse.FromString,
                _registered_method=True)
        self.GetEntity = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/GetEntity',
                request_serializer=tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.GetChildConcepts = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/GetChildConcepts',
                request_serializer=tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.GetDescendantConcepts = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/GetDescendantConcepts',
                request_serializer=tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.GetLIDRRecordConceptsFromTestKit = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/GetLIDRRecordConceptsFromTestKit',
                request_serializer=tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.GetResultConformanceConceptsFromLIDRRecord = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/GetResultConformanceConceptsFromLIDRRecord',
                request_serializer=tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.GetAllowedResultConceptsFromResultConformance = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/GetAllowedResultConceptsFromResultConformance',
                request_serializer=tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
                _registered_method=True)
        self.RebuildSearchIndex = channel.unary_unary(
                '/ai.ica.tinkar.TinkarSearchService/RebuildSearchIndex',
                request_serializer=tinkar__search__pb2.TinkarRebuildIndexRequest.SerializeToString,
                response_deserializer=tinkar__search__pb2.TinkarRebuildIndexResponse.FromString,
                _registered_method=True)


class TinkarSearchServiceServicer(object):
    """gRPC service definition
    """

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConceptSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConceptSearchWithSort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildConcepts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDescendantConcepts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLIDRRecordConceptsFromTestKit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResultConformanceConceptsFromLIDRRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllowedResultConceptsFromResultConformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebuildSearchIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TinkarSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=tinkar__search__pb2.TinkarSearchQueryRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'ConceptSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ConceptSearch,
                    request_deserializer=tinkar__search__pb2.TinkarConceptSearchRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'ConceptSearchWithSort': grpc.unary_unary_rpc_method_handler(
                    servicer.ConceptSearchWithSort,
                    request_deserializer=tinkar__search__pb2.TinkarConceptSearchWithSortRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarConceptSearchWithSortResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=tinkar__search__pb2.TinkarConceptIdRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'GetChildConcepts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildConcepts,
                    request_deserializer=tinkar__search__pb2.TinkarConceptIdRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'GetDescendantConcepts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDescendantConcepts,
                    request_deserializer=tinkar__search__pb2.TinkarConceptIdRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'GetLIDRRecordConceptsFromTestKit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLIDRRecordConceptsFromTestKit,
                    request_deserializer=tinkar__search__pb2.TinkarConceptIdRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'GetResultConformanceConceptsFromLIDRRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResultConformanceConceptsFromLIDRRecord,
                    request_deserializer=tinkar__search__pb2.TinkarConceptIdRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'GetAllowedResultConceptsFromResultConformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllowedResultConceptsFromResultConformance,
                    request_deserializer=tinkar__search__pb2.TinkarConceptIdRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarSearchQueryResponse.SerializeToString,
            ),
            'RebuildSearchIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.RebuildSearchIndex,
                    request_deserializer=tinkar__search__pb2.TinkarRebuildIndexRequest.FromString,
                    response_serializer=tinkar__search__pb2.TinkarRebuildIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.ica.tinkar.TinkarSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.ica.tinkar.TinkarSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TinkarSearchService(object):
    """gRPC service definition
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/Search',
            tinkar__search__pb2.TinkarSearchQueryRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConceptSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/ConceptSearch',
            tinkar__search__pb2.TinkarConceptSearchRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConceptSearchWithSort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/ConceptSearchWithSort',
            tinkar__search__pb2.TinkarConceptSearchWithSortRequest.SerializeToString,
            tinkar__search__pb2.TinkarConceptSearchWithSortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/GetEntity',
            tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildConcepts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/GetChildConcepts',
            tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDescendantConcepts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/GetDescendantConcepts',
            tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLIDRRecordConceptsFromTestKit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/GetLIDRRecordConceptsFromTestKit',
            tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResultConformanceConceptsFromLIDRRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/GetResultConformanceConceptsFromLIDRRecord',
            tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllowedResultConceptsFromResultConformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/GetAllowedResultConceptsFromResultConformance',
            tinkar__search__pb2.TinkarConceptIdRequest.SerializeToString,
            tinkar__search__pb2.TinkarSearchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebuildSearchIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.ica.tinkar.TinkarSearchService/RebuildSearchIndex',
            tinkar__search__pb2.TinkarRebuildIndexRequest.SerializeToString,
            tinkar__search__pb2.TinkarRebuildIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
